<?php

define('LX_TESTING_UTILS_CODECLEANUP_TESTING_DATA_DIR',
    __DIR__ . '/../data/Utils');

define('LX_TESTING_UTILS_CODECLEANUP_TESTING_DATA_DIR_TMP',
    LX_TESTING_UTILS_CODECLEANUP_TESTING_DATA_DIR . '/tmp');

define('LX_TESTING_UTILS_CODECLEANUP_TESTING_DATA_DIR_TASKS',
    LX_TESTING_UTILS_CODECLEANUP_TESTING_DATA_DIR . '/tasks');
